### ISSUE TITLE
Create 'basic info' section page flow

### ISSUE THREAD

**Issue by el-mapache** [18F/eligibility-rules-service#116]
The registration flow (`/basic-info`) represents the first step of the d-snap eligibility form. The following information is requested:

* name ( first, middle, and last)
* DOB (month, day, year)
* sex
* phone number
* email
* country in which they are applying for benefits
* residence address
* mailing address if different

[The invision doc](https://gsa.invisionapp.com/share/HGPCH794DE8#/screens/333864950) shows which fields live on which step of the registration process

**AC**
- [x] Registration information page, basic layout only
- [x] one wizard sub page for each form section, as show in the invision doc
- [x] each page should have validations for the fields which require it. Most fields are not required, so validation shouldn't run on empty fields

**Comment by edmullen** [comment]
![Step 1 - Registrant](https://user-images.githubusercontent.com/2654503/52500631-7c392580-2bac-11e9-909a-a14db1b4953e.png)

![Step 2 - Identity](https://user-images.githubusercontent.com/2654503/52500630-7c392580-2bac-11e9-8b32-f386c573948c.png)

I'm not adding Step 0 - Entry right now because it is in flux. We'll likely need to make some tweaks.
