### ISSUE TITLE
Put together non-MAGI notes 

### ISSUE THREAD

**Issue by alexpandel** [18F/eligibility-rules-service#29]
- Notes to aid Alex in conversation
- Notes will guide Shawnique's research

**Comment by edmullen** [comment]
@alexpandel, I made more progress on this than I remembered. I'd already included the non-MAGI eligibility "pathways" in the [program spreadsheet](https://docs.google.com/spreadsheets/d/1RVRTBu1cTvbgrAAMBsLKoj94nx5lWagSWQ2hrxlf2Gc/edit#gid=0). I'm using _pathways_ rather than programs because they are aspects of Medicaid, not a distinct _program_.

These are the pathways I'm currently thinking of:

* Aged, Blind, and Disabled
* Medically Needy
* Katie Beckett Children with Significant Disabilities Living at Home
* Buy-In for Working People with Disabilities
* Long Term Care
* Section 1915(i) HCBS
* SSI beneficiaries
* Medicare Savings Programs / Dual eligibles

There may be others worth thinking about that will come out. This [Kaiser Family Foundation page](https://www.kff.org/state-category/medicaid-chip/medicaid-eligibility-for-seniors-people-with-disabilities-and-the-medically-needy/) is a good place for initial info. There are four links under "MEDICAID ELIGIBILITY FOR SENIORS, PEOPLE WITH DISABILITIES, AND THE MEDICALLY NEEDY" that lead to details. 

Shawnique is researching eligibility requirements for these pathways in https://github.com/18F/eligibility-rules-service/issues/31.
