### ISSUE TITLE
Review initial repo files

### ISSUE THREAD

**Issue by edmullen** [18F/eligibility-rules-service#4]
Please review the initial three files in the repo.

**Acceptance criteria**

- [x] Review README
- [x] Review CONTRIBUTING
- [x] Review LICENSING
- [x] Make any necessary adjustments

**Comment by edmullen** [comment]
I intended to issue a PR for you to review, but made a mistake on the first commit, so it just went through. Please go back and review the README and other two file. Contributing and License are boilerplate.

**Comment by alexpandel** [comment]
heads up @edmullen, I filed a PR (#8) with some proposed changes (and the thinking behind them in the comments), mostly about the Readme and overall project/repo name. Take a look and let me know what you think - if they look good to you, we'd need to make some changes to some of the wiki files and Contributing.md too for consistency, but otherwise, Contributing.md & Licensing.md look 👍 to me!
